//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klienci()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }

        [Required(ErrorMessage = "Id nie mo¿e byæ puste")]
        public int IDKlienta { get; set; }

        public string NazwaFirmy { get; set; }

        [Required(ErrorMessage = "Imiê nie mo¿e byæ puste")]
        [MinLength(2, ErrorMessage = "Minimalna d³ugoœæ imienia wynosi 2 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ imienia wynosi 250 znaków")]
        public string Imie { get; set; }

        [Required(ErrorMessage = "Nazwisko nie mo¿e byæ puste")]
        [MinLength(3, ErrorMessage = "Minimalna d³ugoœæ nazwiska wynosi 3 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ nazwiska wynosi 250 znaków")]
        public string Nazwisko { get; set; }

        [Required(ErrorMessage = "Adres nie mo¿e byæ pusty")]
        [MinLength(3, ErrorMessage = "Minimalna d³ugoœæ adresu wynosi 3 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ adresu wynosi 255 znaków")]
        public string Adres { get; set; }

        [Required(ErrorMessage = "Kod pocztowy nie mo¿e byæ pusty")]
        [DataType(DataType.PostalCode, ErrorMessage = "Podaj prawid³owy kod pocztowy")]
        public string KodPocztowy { get; set; }

        [Required(ErrorMessage = "Miasto nie mo¿e byæ puste")]
        [MinLength(3, ErrorMessage = "Minimalna d³ugoœæ miasta wynosi 3 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ miasta wynosi 50 znaków")]
        public string Miasto { get; set; }


        [Required(ErrorMessage = "Pañstwo nie mo¿e byæ puste")]
        [MinLength(3, ErrorMessage = "Minimalna d³ugoœæ pañstwa wynosi 3 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ pañstwa wynosi 50 znaków")]
        public string Panstwo { get; set; }

        public Nullable<int> NrTelefonu { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "Nieprwid³owy adres email")]
        [EmailAddress]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
