//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Marki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marki()
        {
            this.Samochody = new HashSet<Samochody>();
        }

        [Required(ErrorMessage = "Id nie mo¿e byæ puste")]
        public int IDMarki { get; set; }

        [Required(ErrorMessage = "Marka nie mo¿e byæ pusta")]
        [MinLength(2, ErrorMessage = "Minimalna d³ugoœæ marki wynosi 2 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ marki wynosi 250 znaków")]
        public string Marka { get; set; }

        [Required(ErrorMessage = "Model nie mo¿e byæ pusty")]
        [MinLength(2, ErrorMessage = "Minimalna d³ugoœæ modelu wynosi 2 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ modelu wynosi 250 znaków")]
        public string Model { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Samochody> Samochody { get; set; }
    }
}
