//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przeglady
    {
        public int IDPrzegladu { get; set; }
        public int IDSamochodu { get; set; }
        public System.DateTime DataPrzegladu { get; set; }
        public System.DateTime WaznoscPrzegladu { get; set; }
    
        public virtual Samochody Samochody { get; set; }
    }
}
