//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochody()
        {
            this.Przeglady = new HashSet<Przeglady>();
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int IDSamochodu { get; set; }
        public int IDWypozyczalni { get; set; }
        public int IDMarki { get; set; }
        public Nullable<int> Rocznik { get; set; }
        public decimal CenaZaDobe { get; set; }
        public string NrRejestracyjny { get; set; }
    
        public virtual Marki Marki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przeglady> Przeglady { get; set; }
        public virtual Wypozyczalnie Wypozyczalnie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
