//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ubezpieczenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ubezpieczenia()
        {
            this.UbezpieczeniaWypozyczenie = new HashSet<UbezpieczeniaWypozyczenie>();
        }

        [Required(ErrorMessage = "Id nie mo¿e byæ puste")]
        public int IDUbezpieczenia { get; set; }

        [Required(ErrorMessage = "Nazwa ubezpieczenia nie mo¿e byæ pusta")]
        [MinLength(3, ErrorMessage = "Minimalna d³ugoœæ nazwy ubezpieczenia wynosi 3 znaki")]
        [MaxLength(250, ErrorMessage = "Maksymalna d³ugoœæ nazwy ubezpieczenia wynosi 250 znaków")]
        public string NazwaUbezpieczenia { get; set; }

        [Required(ErrorMessage = "Wartoœæ ubezpieczenia nie mo¿e byæ pusta")]
        public decimal WartoscUbezpieczenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbezpieczeniaWypozyczenie> UbezpieczeniaWypozyczenie { get; set; }
    }
}
