//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UbezpieczeniaWypozyczenie
    {
        public string NrPolisy { get; set; }
        public int IDWypozyczenia { get; set; }
        public int IDUbezpieczenia { get; set; }
    
        public virtual Ubezpieczenia Ubezpieczenia { get; set; }
        public virtual Wypozyczenia Wypozyczenia { get; set; }
    }
}
