//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wypozyczenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wypozyczenia()
        {
            this.UbezpieczeniaWypozyczenie = new HashSet<UbezpieczeniaWypozyczenie>();
        }

        [Required(ErrorMessage = "Id nie mo¿e byæ puste")]
        public int IDWypozyczenia { get; set; }

        [Required(ErrorMessage = "Id nie mo¿e byæ puste")]
        public int IDPracownika { get; set; }

        [Required(ErrorMessage = "Id nie mo¿e byæ puste")]
        public int IDSamochodu { get; set; }

        [Required(ErrorMessage = "Id nie mo¿e byæ puste")]
        public int IDKlienta { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/mm/yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Podaj prawid³ow¹ datê")]
        public System.DateTime DataWypozyczenia { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/mm/yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Podaj prawid³ow¹ datê")]
        public System.DateTime DataZwrotu { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/mm/yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Podaj prawid³ow¹ datê")]
        public Nullable<System.DateTime> DataFaktycznegoZwrotu { get; set; }

        [Required(ErrorMessage = "Kilometry nie mog¹ byæ puste")]
        public Nullable<int> Kilometry { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Samochody Samochody { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbezpieczeniaWypozyczenie> UbezpieczeniaWypozyczenie { get; set; }
    }
}
