//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wypozyczenia()
        {
            this.UbezpieczeniaWypozyczenie = new HashSet<UbezpieczeniaWypozyczenie>();
        }
    
        public int IDWypozyczenia { get; set; }
        public int IDPracownika { get; set; }
        public int IDSamochodu { get; set; }
        public int IDKlienta { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public System.DateTime DataZwrotu { get; set; }
        public Nullable<System.DateTime> DataFaktycznegoZwrotu { get; set; }
        public Nullable<int> Kilometry { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Samochody Samochody { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbezpieczeniaWypozyczenie> UbezpieczeniaWypozyczenie { get; set; }
    }
}
